### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bee-san** [bee-san/pyWhat#2]
- [x] Positional Arguments
- [x] JSON output, Python Dict API
- [x] Pretty printing of results
- [x] Run regex within regex
- [x] Magic Numbers
- [x] LangDetect
- [x] Credit card
- [x] Name that hash
- [x] #6 
- [x] #5 
- [x] Add strings #3 
- [x] Add more regex #1 
- [x] https://github.com/regexhq
- [x] Add categories / tabs
