### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bee-san** [bee-san/pyWhat#47]
This is my personal ToDo list, if you see something you think you can do please take it from me :-) 
- [x] Add filtration system using distributions 
- [x] Remove language checking stuff
- [ ] Check speed of regex with no boundaries, potentially make all regex boundary-less
